### ISSUE TITLE
How to highlight search term in result HTML?

### ISSUE THREAD

**Issue by alexej-d** [dachcom-digital/pimcore-dynamic-search-index-provider-lucene#13]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I was wondering if there is any documentation on how to highlight the search term in the results? I saw that the AbstractQuery class has a highlightMatches method. Do you use it in a channel action?

**Comment by solverat** [comment]
This is not implement by default. Since the`highlightMatches` is just a simple helper, you could create your own twig helper for that or using a `dynamic_search.document_normalizer` to modify your result!
