### ISSUE TITLE
Pimcore 11 Support

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-dynamic-search-index-provider-lucene#17]

**Comment by solverat** [comment]
Not sure if we're going to maintain this repo within php 8.2. ZendSearch is dead and therefor we need to maintain it by ourself. There are sone issues we've been aware of (some array index issues) and it feels quite odd to keep such old libraries up-to-date.

**Comment by dpfaffenbauer** [comment]
Understandable... So only Elastic Support in the Future then?

**Comment by leuchtdiode** [comment]
We are also using this index provider which is quite handy because we do not need any external dependencies. As we saw, you updated the README a few days ago and it says that there will be a v3.0.0 for Pimcore 11 support. So will there be a pimcore 11 support with ZendSearch? :-)

**Comment by solverat** [comment]
@leuchtdiode yes, we've migrated lucene also. But we experienced some serious issues within ZendSearch itself (`Warning: Undefined array key xy`) on php > 8.1. I was not able to find a proper solution (Don't know, if suppressing it via `?? null` is a good idea).

**Comment by leuchtdiode** [comment]
@solverat thanks for the update, that sounds good. I can have a look at the "undefined index problem" if you send me the affected part of code. Maybe we can figure something out together.

**Comment by solverat** [comment]
@leuchtdiode i think i just fixed it here:

https://github.com/dachcom-digital/ZendSearch/commit/87370c0fc43b5a61bb7460c0dd9e5296521b5998

it feels very very akward to hack such an old library, but hey...

**Comment by leuchtdiode** [comment]
@solverat Nice, thank you. We are using the bundle in several projects, so thanks for your work, we really appreciate it.

I feel you regarding the "hack". But cheers to all the PHP haters, how long lasting this code is with only small adaptions over time :-)
